name: CustomWhiteList
version: 1.0
main: net.MagicWinner.CustomWhiteList.CustomWhiteList
authors: [MagicWinner]
description: Customise ur WhiteList
website: https://vk.com/magicwinner
commands:
  cwl:
